#Requires -RunAsAdministrator
# RevealUI DevEnv Bootstrap
# Run ONCE on a new machine after plugging in the SSD.
# Must be run from an elevated PowerShell 7 session.
#
# Usage:
#   E:\.revealui\bootstrap.ps1
#   E:\.revealui\bootstrap.ps1 -Force   # overwrite existing profile stub

param(
    [switch]$Force
)

Set-StrictMode -Version Latest
$ErrorActionPreference = 'Stop'

Write-Host ""
Write-Host "=== RevealUI DevEnv Bootstrap ===" -ForegroundColor Cyan
Write-Host ""

# --- Step 1: Determine our own location ---
$revealRoot = $PSScriptRoot  # E:\.revealui
Write-Host "[1/5] SSD detected at: $revealRoot" -ForegroundColor Green

# --- Step 2: Set REVEALUI_ROOT environment variable (persisted) ---
Write-Host "[2/5] Setting REVEALUI_ROOT environment variable..."
[System.Environment]::SetEnvironmentVariable('REVEALUI_ROOT', $revealRoot, 'User')
$env:REVEALUI_ROOT = $revealRoot
Write-Host "  REVEALUI_ROOT = $revealRoot" -ForegroundColor Green

# --- Step 3: Set execution policy ---
Write-Host "[3/5] Setting PowerShell execution policy..."
try {
    Set-ExecutionPolicy -ExecutionPolicy RemoteSigned -Scope CurrentUser -Force
    Write-Host "  ExecutionPolicy = RemoteSigned (CurrentUser)" -ForegroundColor Green
} catch {
    Write-Host "  ExecutionPolicy already suitable or could not be set (non-fatal)" -ForegroundColor Yellow
}

# --- Step 4: Write profile stub to Documents (CFA-protected, needs elevation) ---
Write-Host "[4/5] Writing profile stub..."

# Allow pwsh.exe through Controlled Folder Access (CFA/ransomware protection)
$pwshPath = (Get-Process -Id $PID).Path
$cfaApps = (Get-MpPreference).ControlledFolderAccessAllowedApplications
$addedCfa = $false
if (-not $cfaApps -or $pwshPath -notin $cfaApps) {
    Write-Host "  Adding pwsh.exe to Controlled Folder Access allowlist..." -ForegroundColor Cyan
    Add-MpPreference -ControlledFolderAccessAllowedApplications $pwshPath
    $addedCfa = $true
}

$profileDir  = Split-Path $PROFILE.CurrentUserCurrentHost
$profilePath = $PROFILE.CurrentUserCurrentHost

if (-not (Test-Path $profileDir)) {
    New-Item -ItemType Directory -Path $profileDir -Force | Out-Null
}

if ((Test-Path $profilePath) -and -not $Force) {
    Write-Host "  Profile already exists at: $profilePath" -ForegroundColor Yellow
    Write-Host "  Use -Force to overwrite" -ForegroundColor Yellow
} else {
    $stubContent = @'
# RevealUI DevEnv - Profile Stub (auto-generated by bootstrap, do not edit)
# All logic lives on the portable SSD. This stub just finds and loads it.

$revealRoot = $env:REVEALUI_ROOT
if (-not $revealRoot -or -not (Test-Path "$revealRoot\powershell\Modules\RevealUI.DevEnv\RevealUI.DevEnv.psd1" -ErrorAction SilentlyContinue)) {
    # Drive letter may have changed -- scan for our marker
    $revealRoot = Get-Volume | Where-Object { $_.DriveLetter } |
                  ForEach-Object { "$($_.DriveLetter):\.revealui" } |
                  Where-Object { Test-Path "$_\powershell\Modules\RevealUI.DevEnv\RevealUI.DevEnv.psd1" -ErrorAction SilentlyContinue } |
                  Select-Object -First 1
    if ($revealRoot) {
        $env:REVEALUI_ROOT = $revealRoot
        [System.Environment]::SetEnvironmentVariable('REVEALUI_ROOT', $revealRoot, 'User')
    }
}

if ($revealRoot) {
    $modulePath = Join-Path $revealRoot "powershell\Modules"
    if ($env:PSModulePath -notlike "*$modulePath*") {
        $env:PSModulePath = "$modulePath;$env:PSModulePath"
    }
    Import-Module RevealUI.DevEnv -ErrorAction SilentlyContinue
} else {
    Write-Host "RevealUI SSD not detected. Plug in the drive and restart PowerShell." -ForegroundColor Yellow
}
'@
    # Write with UTF-8 BOM for PowerShell compatibility
    $utf8Bom = New-Object System.Text.UTF8Encoding($true)
    [System.IO.File]::WriteAllText($profilePath, $stubContent, $utf8Bom)
    Write-Host "  Written to: $profilePath" -ForegroundColor Green
}

# Remove CFA exception if we added it (leave pwsh.exe allowed — it's safe)
# Keeping it allows future profile edits without re-elevation
if ($addedCfa) {
    Write-Host "  Note: pwsh.exe added to CFA allowlist permanently" -ForegroundColor Gray
}

# --- Step 5: Register scheduled task for auto-mount ---
Write-Host "[5/5] Registering auto-mount scheduled task..."
$taskScript = Join-Path $revealRoot "scripts\create-mount-task.ps1"
if (Test-Path $taskScript) {
    & $taskScript
} else {
    Write-Host "  Task script not found at: $taskScript" -ForegroundColor Yellow
    Write-Host "  Skipping scheduled task registration" -ForegroundColor Yellow
}

Write-Host ""
Write-Host "=== Bootstrap Complete ===" -ForegroundColor Green
Write-Host ""
Write-Host "Next steps:" -ForegroundColor Cyan
Write-Host "  1. Close this window and open a NEW PowerShell"
Write-Host "  2. You should see 'WSL Helpers Loaded!'"
Write-Host "  3. Run: wslstat"
Write-Host ""
Write-Host "For WSL-side setup, run inside WSL:" -ForegroundColor Cyan
Write-Host "  bash /mnt/e/.revealui/bootstrap-wsl.sh" -ForegroundColor White
Write-Host "  (replace 'e' with your actual drive letter if different)" -ForegroundColor Gray
Write-Host ""
