#Requires -RunAsAdministrator
# RevealUI RevStation Bootstrap
# Run ONCE on a new machine after plugging in the SSD.
# Must be run from an elevated PowerShell 7 session.
#
# Usage:
#   E:\.revealui\bootstrap.ps1
#   E:\.revealui\bootstrap.ps1 -Force   # overwrite existing profile stub

param(
    [switch]$Force
)

Set-StrictMode -Version Latest
$ErrorActionPreference = 'Stop'

Write-Host ""
Write-Host "=== RevealUI RevStation Bootstrap ===" -ForegroundColor Cyan
Write-Host ""

# --- Step 1: Determine our own location ---
$revealRoot = $PSScriptRoot  # E:\.revealui
Write-Host "[1/6] SSD detected at: $revealRoot" -ForegroundColor Green

# --- Step 2: Set REVEALUI_ROOT environment variable (persisted) ---
Write-Host "[2/6] Setting REVEALUI_ROOT environment variable..."
[System.Environment]::SetEnvironmentVariable('REVEALUI_ROOT', $revealRoot, 'User')
$env:REVEALUI_ROOT = $revealRoot
Write-Host "  REVEALUI_ROOT = $revealRoot" -ForegroundColor Green

# --- Step 3: Set execution policy ---
Write-Host "[3/6] Setting PowerShell execution policy..."
try {
    Set-ExecutionPolicy -ExecutionPolicy RemoteSigned -Scope CurrentUser -Force
    Write-Host "  ExecutionPolicy = RemoteSigned (CurrentUser)" -ForegroundColor Green
} catch {
    Write-Host "  ExecutionPolicy already suitable or could not be set (non-fatal)" -ForegroundColor Yellow
}

# --- Step 4: Write profile stub to Documents (CFA-protected, needs elevation) ---
Write-Host "[4/6] Writing profile stub..."

# Allow pwsh.exe through Controlled Folder Access (CFA/ransomware protection)
$pwshPath = (Get-Process -Id $PID).Path
$cfaApps = (Get-MpPreference).ControlledFolderAccessAllowedApplications
$addedCfa = $false
if (-not $cfaApps -or $pwshPath -notin $cfaApps) {
    Write-Host "  Adding pwsh.exe to Controlled Folder Access allowlist..." -ForegroundColor Cyan
    Add-MpPreference -ControlledFolderAccessAllowedApplications $pwshPath
    $addedCfa = $true
}

$profileDir  = Split-Path $PROFILE.CurrentUserCurrentHost
$profilePath = $PROFILE.CurrentUserCurrentHost

if (-not (Test-Path $profileDir)) {
    New-Item -ItemType Directory -Path $profileDir -Force | Out-Null
}

if ((Test-Path $profilePath) -and -not $Force) {
    Write-Host "  Profile already exists at: $profilePath" -ForegroundColor Yellow
    Write-Host "  Use -Force to overwrite" -ForegroundColor Yellow
} else {
    $stubContent = @'
# RevealUI RevStation - Profile Stub (auto-generated by bootstrap, do not edit)
# All logic lives on the SSD. This stub just finds and loads it.

$revealRoot = $env:REVEALUI_ROOT
if (-not $revealRoot -or -not (Test-Path "$revealRoot\powershell\Modules\RevealUI.RevStation\RevealUI.RevStation.psd1" -ErrorAction SilentlyContinue)) {
    # Primary: user home (C: drive, always available)
    $homeRoot = Join-Path $env:USERPROFILE ".revealui"
    if (Test-Path "$homeRoot\powershell\Modules\RevealUI.RevStation\RevealUI.RevStation.psd1" -ErrorAction SilentlyContinue) {
        $revealRoot = $homeRoot
    } else {
        # Fallback: scan drives for our marker (SSD)
        $revealRoot = Get-Volume | Where-Object { $_.DriveLetter } |
                      ForEach-Object { "$($_.DriveLetter):\.revealui"; "$($_.DriveLetter):\professional\.revealui" } |
                      Where-Object { Test-Path "$_\powershell\Modules\RevealUI.RevStation\RevealUI.RevStation.psd1" -ErrorAction SilentlyContinue } |
                      Select-Object -First 1
    }
    if ($revealRoot) {
        $env:REVEALUI_ROOT = $revealRoot
        [System.Environment]::SetEnvironmentVariable('REVEALUI_ROOT', $revealRoot, 'User')
    }
}

if ($revealRoot) {
    $modulePath = Join-Path $revealRoot "powershell\Modules"
    if ($env:PSModulePath -notlike "*$modulePath*") {
        $env:PSModulePath = "$modulePath;$env:PSModulePath"
    }
    Import-Module RevealUI.RevStation -ErrorAction SilentlyContinue
} else {
    Write-Host "RevealUI SSD not detected. Plug in the drive and restart PowerShell." -ForegroundColor Yellow
}
'@
    # Write with UTF-8 BOM for PowerShell compatibility
    $utf8Bom = New-Object System.Text.UTF8Encoding($true)
    [System.IO.File]::WriteAllText($profilePath, $stubContent, $utf8Bom)
    Write-Host "  Written to: $profilePath" -ForegroundColor Green
}

# Remove CFA exception if we added it (leave pwsh.exe allowed — it's safe)
# Keeping it allows future profile edits without re-elevation
if ($addedCfa) {
    Write-Host "  Note: pwsh.exe added to CFA allowlist permanently" -ForegroundColor Gray
}

# --- Step 5: Register scheduled task for auto-mount ---
Write-Host "[5/6] Registering auto-mount scheduled task..."
# create-mount-task.ps1 was folded into the RevStation module as
# Register-DevMountTask. Call the cmdlet directly and fail loudly — the old
# warn-and-skip on the missing script left fresh hosts without the
# WSL-Mount-DevDrive task while still printing "Bootstrap Complete".
Import-Module (Join-Path $revealRoot 'powershell\Modules\RevealUI.RevStation') -Force
Register-DevMountTask
Write-Host "  WSL-Mount-DevDrive task registered (logon + USB + 30-min triggers)" -ForegroundColor Green

# --- Step 6: Wire fleet-wide pre-push hook (M-11) ---
# Spec: internal fleet-security-hardening lane, meta-durability-fixes §M-11
#
# Class killed: absent server-side branch protection on private repos (T0-15;
# GitHub Free rejects branch-protection API on private repos and owner has
# rejected the Team upgrade). The pre-push hook script lives in-repo at
# $revealRoot\git-hooks\pre-push and is deployed globally via core.hooksPath
# so every clone on this Windows host inherits it.
#
# Conflict handling (per design): fail-loudly when the user already has a
# different global core.hooksPath. Silent overwrite would clobber another
# tool's setup; silent skip would silently disable M-11. The user decides.
Write-Host "[6/6] Wiring fleet-wide pre-push hook (M-11)..."
$hooksDir   = Join-Path $revealRoot "git-hooks"
$prePushHook = Join-Path $hooksDir "pre-push"

if (-not (Test-Path $prePushHook)) {
    Write-Host "  WARNING: $prePushHook not found — skipping M-11 wiring" -ForegroundColor Yellow
} elseif (-not (Get-Command git -ErrorAction SilentlyContinue)) {
    Write-Host "  WARNING: git not on PATH — skipping M-11 wiring" -ForegroundColor Yellow
} else {
    # Read current global hooksPath. `git config --get` exits 1 when unset;
    # tolerate that without tripping the script.
    $existing = $null
    try {
        $existing = (& git config --global --get core.hooksPath 2>$null)
    } catch {
        $existing = $null
    }
    if ($LASTEXITCODE -ne 0) { $existing = $null }

    if ([string]::IsNullOrWhiteSpace($existing)) {
        & git config --global core.hooksPath $hooksDir
        Write-Host "  Set: global core.hooksPath = $hooksDir" -ForegroundColor Green
    } elseif ($existing -eq $hooksDir) {
        Write-Host "  global core.hooksPath already = $hooksDir (no-op)" -ForegroundColor Gray
    } else {
        # Fail loudly. Do not silently overwrite (would clobber another tool)
        # or silently skip (would disable M-11). Owner decides.
        Write-Host "  ERROR: global core.hooksPath is already set to a DIFFERENT path:" -ForegroundColor Red
        Write-Host "    current: $existing" -ForegroundColor Red
        Write-Host "    revkit:  $hooksDir" -ForegroundColor Red
        Write-Host "  Resolve manually, then re-run bootstrap:" -ForegroundColor Yellow
        Write-Host "    git config --global --unset core.hooksPath" -ForegroundColor Yellow
        Write-Host "  Then: & '$PSCommandPath'" -ForegroundColor Yellow
        throw "core.hooksPath conflict (M-11)"
    }
    Write-Host "  M-11 active: pre-push will reject direct/force/unsigned pushes to main + test" -ForegroundColor Green
    Write-Host "  Per-repo escape hatch: git config revealui.hooks.no-protection true" -ForegroundColor Gray
}

Write-Host ""
Write-Host "=== Bootstrap Complete ===" -ForegroundColor Green
Write-Host ""
Write-Host "Next steps:" -ForegroundColor Cyan
Write-Host "  1. Close this window and open a NEW PowerShell"
Write-Host "  2. You should see 'WSL Helpers Loaded!'"
Write-Host "  3. Run: wslstat"
Write-Host ""
Write-Host "For WSL-side setup, run inside WSL:" -ForegroundColor Cyan
# Convert Windows path to /mnt/<drive>/<rest>
$revealRootDrive = $revealRoot.Substring(0, 1).ToLower()
$revealRootRest  = $revealRoot.Substring(2) -replace '\\', '/'
$revealRootWsl   = "/mnt/$revealRootDrive$revealRootRest"
Write-Host "  bash $revealRootWsl/bootstrap-wsl.sh" -ForegroundColor White
Write-Host "  (or from portable SSD: bash /mnt/<drive>/.revealui/bootstrap-wsl.sh)" -ForegroundColor Gray
Write-Host ""
