#!/usr/bin/env bash
# worktree-env.sh — Rift-inspired deterministic ports + claim registry (RevKit).
#
# Parallel agents need isolation for *runtime* (ports) and *coordination*
# (who owns which surface). Code ownership still requires modular product
# files (revealui page-blocks modules); this lib only covers launcher ops.
#
# Port formula (same spirit as Rift bootstrap):
#   BASE = (sha1(name) numeric slice % 7000) + 3000  → 3000–9999
#   MARKETING/VITE=BASE, ADMIN=BASE+1, DOCS=BASE+2, API=BASE+3, …
#
# Claims store (PID-aware, TTL):
#   ~/.local/share/revealui/claims/<repo>/<surface-slug>.json
#
# shellcheck shell=bash

# Default fleet worktree parent (matches .jv / AGENTS.md convention).
RFG_WT_ROOT="${RFG_WT_ROOT:-$HOME/revfleet/.wt}"
REVEALUI_CLAIMS_DIR="${REVEALUI_CLAIMS_DIR:-$HOME/.local/share/revealui/claims}"
REVEALUI_WT_ENV_DIR="${REVEALUI_WT_ENV_DIR:-$HOME/.local/share/revealui/worktree-env}"

# ---------------------------------------------------------------------------
# Ports
# ---------------------------------------------------------------------------

# Hash worktree label → base port in 3000–9999 (stable for the same name).
rfg_port_base_for() {
  local name="$1"
  local hash hex num
  if command -v sha1sum >/dev/null 2>&1; then
    hash="$(printf '%s' "$name" | sha1sum | awk '{print $1}')"
  elif command -v shasum >/dev/null 2>&1; then
    hash="$(printf '%s' "$name" | shasum | awk '{print $1}')"
  else
    # Fallback: cksum is weaker but always present on POSIX-ish systems.
    hash="$(printf '%s' "$name" | cksum | awk '{print $1}')"
  fi
  # Strip non-digits; take first 4 digit chars when possible.
  hex="$(printf '%s' "$hash" | tr -cd '0-9')"
  if [ -z "$hex" ]; then
    hex="$(printf '%s' "$hash" | od -An -tu4 | tr -d ' \n' | head -c 8)"
  fi
  num="${hex:0:4}"
  if [ -z "$num" ]; then num=0; fi
  # bash arithmetic: BASE in 3000..9999
  echo $(( (10#$num % 7000) + 3000 ))
}

# Derive multi-service ports from a base (or from a name).
# Prints KEY=value lines suitable for .env.worktree.
rfg_port_env_lines() {
  local name_or_base="$1"
  local base
  case "$name_or_base" in
    '' | *[!0-9]*) base="$(rfg_port_base_for "$name_or_base")" ;;
    *) base="$name_or_base" ;;
  esac
  cat <<EOF
# Generated by rfg worktree-env (Rift-inspired). Do not commit.
# Worktree label hash → base port ${base} (3000–9999).
RFG_PORT_BASE=${base}
PORT=${base}
VITE_PORT=${base}
MARKETING_PORT=${base}
ADMIN_PORT=$((base + 1))
DOCS_PORT=$((base + 2))
API_PORT=$((base + 3))
SERVER_PORT=$((base + 3))
PREVIEW_PORT=$((base + 4))
ELECTRIC_PORT=$((base + 5))
EOF
}

# Write .env.worktree inside the worktree + mirror under ~/.local/share.
# Args: worktree_path [label]
rfg_write_worktree_env() {
  local wt_path="$1"
  local label="${2:-}"
  local project mirror_dir env_file mirror_file

  if [ -z "$label" ]; then
    label="$(basename "$wt_path")"
  fi
  project="$(basename "$(dirname "$wt_path")")"
  # Prefer repo name when path is …/revfleet/.wt/<label>
  if [ "$(basename "$(dirname "$wt_path")")" = ".wt" ]; then
    project="fleet"
  fi
  # If worktree is a git checkout of a named product, use that.
  if [ -d "$wt_path/.git" ] || [ -f "$wt_path/.git" ]; then
    local top
    top="$(git -C "$wt_path" rev-parse --show-toplevel 2>/dev/null || true)"
    if [ -n "$top" ]; then
      project="$(basename "$top")"
    fi
  fi

  env_file="$wt_path/.env.worktree"
  mirror_dir="$REVEALUI_WT_ENV_DIR/$project"
  mirror_file="$mirror_dir/${label}.env"

  mkdir -p "$wt_path" "$mirror_dir"
  {
    echo "# rfg worktree env — $(date -u +%Y-%m-%dT%H:%M:%SZ)"
    echo "RFG_WORKTREE_NAME=$label"
    echo "RFG_WORKTREE_PATH=$wt_path"
    rfg_port_env_lines "$label"
  } >"$env_file"
  cp -f "$env_file" "$mirror_file"

  # Do not mutate product .gitignore (would dirty the tree). Mirror is SSOT backup;
  # callers should list .env.worktree in repo gitignore once (see rfg-launcher.md).

  echo "$env_file"
}

# ---------------------------------------------------------------------------
# Claims
# ---------------------------------------------------------------------------

_rfg_slugify() {
  printf '%s' "$1" | tr '[:upper:]' '[:lower:]' | sed -E 's/[^a-z0-9]+/-/g; s/^-+//; s/-+$//; s/-+/-/g'
}

_rfg_claim_path() {
  local repo="$1" surface="$2"
  local slug
  slug="$(_rfg_slugify "$surface")"
  echo "$REVEALUI_CLAIMS_DIR/$repo/${slug}.json"
}

# Return 0 if claim file is held by a live process or unexpired lease.
_rfg_claim_is_active() {
  local file="$1"
  [ -f "$file" ] || return 1
  local pid expires now
  pid="$(sed -n 's/.*"pid"[[:space:]]*:[[:space:]]*\([0-9][0-9]*\).*/\1/p' "$file" | head -1)"
  expires="$(sed -n 's/.*"expiresAt"[[:space:]]*:[[:space:]]*"\([^"]*\)".*/\1/p' "$file" | head -1)"
  if [ -n "$pid" ] && kill -0 "$pid" 2>/dev/null; then
    return 0
  fi
  if [ -n "$expires" ]; then
    now="$(date -u +%s)"
    # Try GNU date; fall back to keeping claim if parse fails.
    local exp_s
    exp_s="$(date -u -d "$expires" +%s 2>/dev/null || date -u -j -f '%Y-%m-%dT%H:%M:%SZ' "$expires" +%s 2>/dev/null || echo "")"
    if [ -n "$exp_s" ] && [ "$now" -lt "$exp_s" ]; then
      return 0
    fi
  fi
  return 1
}

_rfg_json_str() {
  # Minimal JSON string escape (no control chars expected in claim fields).
  local s="$1"
  s="${s//\\/\\\\}"
  s="${s//\"/\\\"}"
  printf '"%s"' "$s"
}

# Acquire claim. Args: repo surface [ttl_hours=24]
# Env: RFG_CLAIM_FORCE=1 to steal; RFG_CLAIM_AGENT; RFG_CLAIM_WORKTREE; RFG_CLAIM_BRANCH
rfg_claim_acquire() {
  local repo="$1" surface="$2" ttl_h="${3:-24}"
  local file dir now exp pid agent worktree branch
  file="$(_rfg_claim_path "$repo" "$surface")"
  dir="$(dirname "$file")"
  mkdir -p "$dir"

  if [ -f "$file" ] && _rfg_claim_is_active "$file"; then
    if [ "${RFG_CLAIM_FORCE:-0}" != 1 ]; then
      echo "claim held: $file" >&2
      cat "$file" >&2
      return 1
    fi
  fi

  now="$(date -u +%Y-%m-%dT%H:%M:%SZ)"
  if date -u -d "+${ttl_h} hours" +%Y-%m-%dT%H:%M:%SZ >/dev/null 2>&1; then
    exp="$(date -u -d "+${ttl_h} hours" +%Y-%m-%dT%H:%M:%SZ)"
  else
    exp="$(date -u -v+"${ttl_h}"H +%Y-%m-%dT%H:%M:%SZ 2>/dev/null || echo "$now")"
  fi
  pid="$$"
  agent="${RFG_CLAIM_AGENT:-${USER:-unknown}}"
  worktree="${RFG_CLAIM_WORKTREE:-${PWD:-}}"
  branch="${RFG_CLAIM_BRANCH:-}"
  if [ -z "$branch" ] && command -v git >/dev/null 2>&1; then
    branch="$(git -C "${worktree:-.}" rev-parse --abbrev-ref HEAD 2>/dev/null || true)"
  fi

  cat >"$file" <<EOF
{
  "surface": $(_rfg_json_str "$surface"),
  "repo": $(_rfg_json_str "$repo"),
  "worktree": $(_rfg_json_str "$worktree"),
  "branch": $(_rfg_json_str "$branch"),
  "agent": $(_rfg_json_str "$agent"),
  "pid": $pid,
  "claimedAt": "$now",
  "expiresAt": "$exp"
}
EOF
  echo "$file"
}

rfg_claim_release() {
  local repo="$1" surface="$2"
  local file
  file="$(_rfg_claim_path "$repo" "$surface")"
  if [ -f "$file" ]; then
    rm -f "$file"
    echo "released $repo / $surface"
  else
    echo "no claim file for $repo / $surface" >&2
    return 1
  fi
}

rfg_claim_list() {
  local repo="${1:-}"
  local root="$REVEALUI_CLAIMS_DIR"
  [ -d "$root" ] || { echo "(no claims dir)"; return 0; }
  if [ -n "$repo" ]; then
    [ -d "$root/$repo" ] || { echo "(no claims for $repo)"; return 0; }
    find "$root/$repo" -type f -name '*.json' -print 2>/dev/null | sort
  else
    find "$root" -type f -name '*.json' -print 2>/dev/null | sort
  fi
}

rfg_claim_check() {
  local repo="$1" surface="$2"
  local file
  file="$(_rfg_claim_path "$repo" "$surface")"
  if _rfg_claim_is_active "$file"; then
    echo "active"
    cat "$file"
    return 0
  fi
  if [ -f "$file" ]; then
    echo "stale"
    cat "$file"
    return 2
  fi
  echo "free"
  return 1
}

rfg_claim_sweep() {
  local f
  local n=0
  [ -d "$REVEALUI_CLAIMS_DIR" ] || return 0
  while IFS= read -r f; do
    [ -n "$f" ] || continue
    if ! _rfg_claim_is_active "$f"; then
      rm -f "$f"
      n=$((n + 1))
      echo "swept $f"
    fi
  done < <(find "$REVEALUI_CLAIMS_DIR" -type f -name '*.json' 2>/dev/null)
  echo "swept $n stale claim(s)"
}
