[boot]
systemd=true

[automount]
enabled = true
root = /mnt/
options = "metadata,umask=22,fmask=11"
mountFsTab = false

[network]
generateHosts = false
generateResolvConf = false

[interop]
enabled = true
appendWindowsPath = false

[user]
default = joshua-v-dev
